### ISSUE TITLE
How to disable 'ApplyMica' after use - Or - How to disable 'ApplyMica' for a specific widget in 'customtkinter'?

### ISSUE THREAD

**Issue by hassan-anari** [martinet101/pymica#21]
Hello @marticliment, thank you very much for making this library because it has a great impact on the appearance of the program!
I use the following code to apply Mica style:
```python
class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()
        self.title("Talayar")
        self.geometry(center(self, 720, 1280))
        self.resizable(False, False)
        customtkinter.set_appearance_mode('dark')
        mode = MicaTheme.DARK 
        style = MicaStyle.ALT 
        hwnd = self.frame()  
        ApplyMica(HWND=hwnd, Theme=mode, Style=style)
```
This code is applied globally to the entire program and all widgets.
Now my problem is that I want to put several photos in the program, but the color of the photo gets mixed up... For example, look at the photo below, both photos are the same, but the colors are different:

![pic](https://github.com/user-attachments/assets/d7d124f1-c9c1-4662-9328-dd3f15c503ba)

Now the question is, how can I fix this problem and 'ApplyMica' does not affect the photos?

**Comment by marticliment** [comment]
Are your photos semi-transparent?

I suggest drawing an opaque rectangle/background under your photos

**Comment by hassan-anari** [comment]
@marticliment, Thank you for your reply!
No, the photos are not semi-transparent. You can see the original photo in the below:

![Screenshot 2024-07-30 195245](https://github.com/user-attachments/assets/35c13684-55d6-46a2-b443-1876f1ca4db1)

I drew two black and white rectangles under the photo, but it didn't change:

![Screenshot 2024-07-30 200547](https://github.com/user-attachments/assets/c1938fcb-fb98-4f43-9553-a286d5e81631)

![Screenshot 2024-07-30 200618](https://github.com/user-attachments/assets/29ea7e86-ab01-4f28-9127-45c72d68a758)

What should I do? thank you.

**Comment by marticliment** [comment]
It is interesting that the black rectangle is also showing tinted...

I have never seen this issue, could it be caused by customtkinter? Please try to draw the same picture on plain tkinter, with win32mica

**Comment by hassan-anari** [comment]
@marticliment, The problem still persists...

![Screenshot 2024-07-30 221728](https://github.com/user-attachments/assets/c3f25583-743a-4b27-8f8c-74cd7d48ae1b)

![Screenshot 2024-07-30 2221](https://github.com/user-attachments/assets/00ff10f8-f182-4cff-b2d2-41e36741541a)

it's very interesting!

**Comment by marticliment** [comment]
Try to do something: Tk draws transparency by specifying the "transparency" color, and then rendering it transparent on the window. Any text, image or element that contains that color will have that color rendered transparent. 

See the following code:
![image](https://github.com/user-attachments/assets/4bcad62f-92eb-4036-adfb-1569dea5b567)


Try to add the app.configure and the app.wm_attributes, but set a random color to the color, instead of black

**Comment by hassan-anari** [comment]
@marticliment, The above code is considered an improvement, but unfortunately, the style of the program is messed up...

By applying the code above:

![Screenshot 2024-07-31 160028](https://github.com/user-attachments/assets/13f5fc0e-584a-4389-a3e1-6edd2a53f1af)

Without applying the code above:

![Screenshot 2024-07-31 155953](https://github.com/user-attachments/assets/b630bfd5-2bcd-4c12-a030-1342567d7de9)

**Comment by marticliment** [comment]
Try to set the transparent background to #16191e, which is the background color used by your Tkinter flavour

**Comment by hassan-anari** [comment]
@marticliment, 'ApplyMica' is applied to the background but not to the widgets...

After:

![Screenshot 2024-07-31 223007](https://github.com/user-attachments/assets/f26cfbbf-95f7-48b9-aaf6-a8915c8f7b67)

Before:

![Screenshot 2024-07-31 160028](https://github.com/user-attachments/assets/5e972f53-b953-4de6-ae23-79fd520bf0f2)

**Comment by marticliment** [comment]
I am afraid I then don't know what is happening. looks like customtkinter is using a different method to render transparencies, and that it is affecting your image, and virtually any control.

I am afraid I can't help you with that, since I don't know how customtkinter works here.

**Comment by hassan-anari** [comment]
@marticliment, You have helped a lot so far and I am grateful to you!
I will message the owner of 'customtkinter' and ask him to look at this issue and explain if he can.

**Comment by hassan-anari** [comment]
@marticliment... With the help of @Akascape, the problem is finally solved and that's great.
